// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy9m6TRwrN_Y22TPGvJ-FEWgnutWUkYfg',
    appId: '1:88958691224:web:512fc10d200a2b9ad2eded',
    messagingSenderId: '88958691224',
    projectId: 'qbank-a6482',
    authDomain: 'qbank-a6482.firebaseapp.com',
    storageBucket: 'qbank-a6482.firebasestorage.app',
    measurementId: 'G-6CZ3EZH6C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJ0hiUGwlCC9RRHZuOeZKl9rXxY4opHc',
    appId: '1:88958691224:android:d03251dbccd36b5ed2eded',
    messagingSenderId: '88958691224',
    projectId: 'qbank-a6482',
    storageBucket: 'qbank-a6482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOd_0Xb5lJYlwpGvr051mHFcVGivz2efI',
    appId: '1:88958691224:ios:856338c5a7d7c911d2eded',
    messagingSenderId: '88958691224',
    projectId: 'qbank-a6482',
    storageBucket: 'qbank-a6482.firebasestorage.app',
    iosBundleId: 'com.oss.qbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOd_0Xb5lJYlwpGvr051mHFcVGivz2efI',
    appId: '1:88958691224:ios:856338c5a7d7c911d2eded',
    messagingSenderId: '88958691224',
    projectId: 'qbank-a6482',
    storageBucket: 'qbank-a6482.firebasestorage.app',
    iosBundleId: 'com.oss.qbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy9m6TRwrN_Y22TPGvJ-FEWgnutWUkYfg',
    appId: '1:88958691224:web:6822bd0a13346d92d2eded',
    messagingSenderId: '88958691224',
    projectId: 'qbank-a6482',
    authDomain: 'qbank-a6482.firebaseapp.com',
    storageBucket: 'qbank-a6482.firebasestorage.app',
    measurementId: 'G-NLDSN5P6KM',
  );
}
